workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "ayush.muley.paintingai"
      android_signing:
        - keystore_reference: AMPAINT_KEYSTORE
          keystore_password: "${{AMPAINT_KEYSTORE_PASSWORD}}"
          key_alias: "my-key-alias"
          key_password: "${{AMPAINT_KEY_PASSWORD}}"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Copy web assets to Android
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

secrets:
  AMPAINT_KEYSTORE:
    file: my-release-key.keystore
  AMPAINT_KEYSTORE_PASSWORD:
    required: true
  AMPAINT_KEY_PASSWORD:
    required: true
