workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60 # Maximum build duration in minutes
    environment:
      vars:
        PACKAGE_NAME: "ayush.muley.paintingai"
    # Define your signing configuration here, referencing the keystore from Codemagic UI
    android_signing:
      - keystore_reference: AMPAINT_KEYSTORE
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Copy web assets to Android
        script: npx cap sync android
      - name: Build Android release outputs
        working_directory: android # Optional: makes subsequent commands run in the 'android' directory
        script: |
          # Apply signing using the Codemagic provided variables
          # Codemagic will automatically inject the necessary environment variables for signing
          # when `android_signing` is configured as shown above.
          ./gradlew assembleRelease bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk # More specific path for APKs
      - android/app/build/outputs/bundle/release/*.aab # More specific path for AABs